/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const JobType = IDL.Variant({
  'remote' : IDL.Null,
  'internship' : IDL.Null,
  'contract' : IDL.Null,
  'freelance' : IDL.Null,
  'part_time' : IDL.Null,
  'full_time' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : Time,
  'postedBy' : IDL.Principal,
  'salary' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'appliedAt' : Time,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
});
export const EmployerProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'industry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'employer' : IDL.Null,
  'job_seeker' : IDL.Null,
});
export const JobSeekerProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'experience' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'employerProfile' : IDL.Opt(EmployerProfile),
  'role' : UserRole,
  'jobSeekerProfile' : IDL.Opt(JobSeekerProfile),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createEmployerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createJobSeekerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Nat], [ApplicationStatus], ['query']),
  'getApplicationsByApplicant' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getApplicationsByJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  'getJobsByCompany' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  'getJobsByJobType' : IDL.Func([JobType], [IDL.Vec(JobListing)], ['query']),
  'getJobsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  'getJobsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobType = IDL.Variant({
    'remote' : IDL.Null,
    'internship' : IDL.Null,
    'contract' : IDL.Null,
    'freelance' : IDL.Null,
    'part_time' : IDL.Null,
    'full_time' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : Time,
    'postedBy' : IDL.Principal,
    'salary' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'appliedAt' : Time,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
  });
  const EmployerProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'industry' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'employer' : IDL.Null,
    'job_seeker' : IDL.Null,
  });
  const JobSeekerProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'experience' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'employerProfile' : IDL.Opt(EmployerProfile),
    'role' : UserRole,
    'jobSeekerProfile' : IDL.Opt(JobSeekerProfile),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createEmployerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createJobSeekerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getApplicationStatus' : IDL.Func(
        [IDL.Nat],
        [ApplicationStatus],
        ['query'],
      ),
    'getApplicationsByApplicant' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getApplicationsByJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getJobsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobsByCompany' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
    'getJobsByJobType' : IDL.Func([JobType], [IDL.Vec(JobListing)], ['query']),
    'getJobsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };