/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null };
export interface EmployerProfile {
  'bio' : string,
  'name' : string,
  'company' : string,
  'industry' : string,
}
export interface JobApplication {
  'id' : bigint,
  'status' : ApplicationStatus,
  'applicant' : Principal,
  'appliedAt' : Time,
  'jobId' : bigint,
  'coverLetter' : string,
}
export interface JobListing {
  'id' : bigint,
  'title' : string,
  'postedAt' : Time,
  'postedBy' : Principal,
  'salary' : string,
  'jobType' : JobType,
  'description' : string,
  'company' : string,
  'category' : string,
  'location' : string,
}
export interface JobSeekerProfile {
  'bio' : string,
  'name' : string,
  'experience' : Array<string>,
  'skills' : Array<string>,
}
export type JobType = { 'remote' : null } |
  { 'internship' : null } |
  { 'contract' : null } |
  { 'freelance' : null } |
  { 'part_time' : null } |
  { 'full_time' : null };
export type Time = bigint;
export interface UserProfile {
  'employerProfile' : [] | [EmployerProfile],
  'role' : UserRole,
  'jobSeekerProfile' : [] | [JobSeekerProfile],
}
export type UserRole = { 'employer' : null } |
  { 'job_seeker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createEmployerProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createJobSeekerProfile' : ActorMethod<
    [string, string, Array<string>, Array<string>],
    undefined
  >,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllJobs' : ActorMethod<[], Array<JobListing>>,
  'getApplicationStatus' : ActorMethod<[bigint], ApplicationStatus>,
  'getApplicationsByApplicant' : ActorMethod<
    [Principal],
    Array<JobApplication>
  >,
  'getApplicationsByJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getJobsByCategory' : ActorMethod<[string], Array<JobListing>>,
  'getJobsByCompany' : ActorMethod<[string], Array<JobListing>>,
  'getJobsByJobType' : ActorMethod<[JobType], Array<JobListing>>,
  'getJobsByLocation' : ActorMethod<[string], Array<JobListing>>,
  'getJobsByTitle' : ActorMethod<[string], Array<JobListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJob' : ActorMethod<
    [string, string, string, string, string, string, JobType],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, string, string, JobType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];